/** A starter deck: common English words and their Indonesian meaning. */
export const SAMPLE_NAME = 'English – Indonesian basics'

export const SAMPLE: [string, string][] = [
  ['hello', 'halo'],
  ['thank you', 'terima kasih'],
  ['please', 'tolong / silakan'],
  ['sorry', 'maaf'],
  ['good morning', 'selamat pagi'],
  ['good night', 'selamat malam'],
  ['water', 'air'],
  ['rice', 'nasi'],
  ['to eat', 'makan'],
  ['to drink', 'minum'],
  ['house', 'rumah'],
  ['school', 'sekolah'],
  ['friend', 'teman'],
  ['family', 'keluarga'],
  ['book', 'buku'],
  ['market', 'pasar'],
  ['money', 'uang'],
  ['today', 'hari ini'],
  ['tomorrow', 'besok'],
  ['yesterday', 'kemarin'],
  ['big', 'besar'],
  ['small', 'kecil'],
  ['hot', 'panas'],
  ['cold', 'dingin'],
  ['beautiful', 'cantik / indah'],
  ['to go', 'pergi'],
  ['to come', 'datang'],
  ['to buy', 'membeli'],
  ['to read', 'membaca'],
  ['to write', 'menulis'],
  ['where', 'di mana'],
  ['how much', 'berapa'],
  ['delicious', 'enak'],
  ['happy', 'senang'],
  ['tired', 'capek / lelah'],
  ['rain', 'hujan'],
  ['street', 'jalan'],
  ['car', 'mobil'],
  ['motorbike', 'motor'],
  ['work', 'kerja'],
]
